### ISSUE TITLE
OpenAI Gym Environment

### ISSUE THREAD

**Issue by Tien-Cheng** [kiritowu/pong-ai#2]
Requirements
- [ ] Must expose same API as OpenAI Gym
- [ ] Must be able to run on AI lab computers

**Comment by Tien-Cheng** [comment]
Requirements
- [ ] Must expose same API as OpenAI Gym
- [ ] Must be able to run on AI lab computers
- [ ] Pong Game must be able to be played with all features (control the paddle, ball physics, scorekeeping)
- [ ] Must be able to accept input from an AI player 
- [ ] Must be able to accept input from a human player

**Comment by kiritowu** [comment]
This issue is closed since OpenAI Gym only provides AI (hard-coded) to AI pong environment which is only suitable for training of RL Agent. As such, a separate game engine is developed with `pygame` in [Pong Game](https://github.com/kiritowu/pong-ai/issues/4) with as much UI similarity as the gym environment(where the AI is trained in) to reduce covariate shift.
